Do not fail when mojo execution descriptor does not have a phase
When a mojo execution descriptor comes without a phase, the row format calculated
by a TableDescriptor was malformed.
It now fallback to the mojo execution lifecycle phase.

[ERROR] Failed to execute goal fr.jcgay.maven.plugins:buildplan-maven-plugin:1.1-SNAPSHOT:list (default-cli) on project jcgay-build-configuration: Execution default-cli of goal fr.jcgay.maven.plugins:buildplan-maven-plugin:1.1-SNAPSHOT:list failed: %-0s -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal fr.jcgay.maven.plugins:buildplan-maven-plugin:1.1-SNAPSHOT:list (default-cli) on project jcgay-build-configuration: Execution default-cli of goal fr.jcgay.maven.plugins:buildplan-maven-plugin:1.1-SNAPSHOT:list failed: %-0s
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal fr.jcgay.maven.plugins:buildplan-maven-plugin:1.1-SNAPSHOT:list failed: %-0s
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.util.MissingFormatWidthException: %-0s
	at java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:2954)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2725)
	at java.util.Formatter.parse(Formatter.java:2560)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2925)
	at fr.jcgay.maven.plugin.buildplan.ListMojo.tableHead(ListMojo.java:64)
	at fr.jcgay.maven.plugin.buildplan.ListMojo.execute(ListMojo.java:44)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more